# Generated by Django 4.2.2 on 2023-06-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.IntegerField(choices=[(0, '10AM'), (1, '11AM'), (2, '12AM'), (3, '1PM'), (4, '2PM'), (5, '3PM'), (6, '4PM'), (7, '5PM'), (8, '6PM'), (9, '7PM')]),
        ),
    ]
