# Generated by Django 4.2.2 on 2023-06-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_rename_review_body_review_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
